# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_auto_20180626_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='pic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
