# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_types_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='typename',
            field=models.CharField(max_length=20),
        ),
    ]
